name: ReadPaper
options:
  minimumXcodeGenVersion: 2.42.0
  deploymentTarget:
    macOS: "14.0"
packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.7.0
  SwiftOpenAI:
    url: https://github.com/jamesrochabrun/SwiftOpenAI
    from: 4.3.3
  Readability:
    path: swift-readability
targets:
  ReadPaper:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ReadPaper
    dependencies:
      - package: SwiftSoup
      - package: SwiftOpenAI
      - package: Readability
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yiyan.ReadPaper
        PRODUCT_NAME: Freddie
        PRODUCT_MODULE_NAME: ReadPaper
        DEVELOPMENT_LANGUAGE: en
        INFOPLIST_FILE: ReadPaper/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Freddie
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 6.0
        ENABLE_TESTABILITY: YES
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 13
        MARKETING_VERSION: 0.2.2
  ReadPaperTests:
    type: bundle.unit-test
    platform: macOS
    hostApplication: ReadPaper
    deploymentTarget: "14.0"
    sources:
      - path: ReadPaperTests
    dependencies:
      - target: ReadPaper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yiyan.ReadPaperTests
        PRODUCT_NAME: ReadPaperTests
        DEVELOPMENT_LANGUAGE: en
        INFOPLIST_FILE: ReadPaperTests/Info.plist
        SWIFT_VERSION: 6.0
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Freddie.app/Contents/MacOS/Freddie
        BUNDLE_LOADER: $(TEST_HOST)
schemes:
  ReadPaper:
    build:
      targets:
        ReadPaper: all
        ReadPaperTests: [test]
    test:
      targets:
        - ReadPaperTests
