import XCTest
@testable import ReadPaper

final class PaperDigestExportPolicyTests: XCTestCase {
    private var tempDirectory: URL!

    override func setUpWithError() throws {
        tempDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        if let tempDirectory {
            try? FileManager.default.removeItem(at: tempDirectory)
        }
        tempDirectory = nil
    }

    func testMarkdownIncludesPaperMetadataAbstractAndNotes() throws {
        let exportDate = Date(timeIntervalSince1970: 1_700_000_000)
        let paper = Paper(
            arxivID: "2303.08774",
            title: "A Test Paper",
            abstractText: "This is the abstract.\nIt has a second line.",
            authors: ["Ada Lovelace", "Alan Turing"]
        )
        let keptNote = Note(
            paperID: paper.id,
            quote: "Important quote",
            body: "My reading note",
            pageIndex: 2,
            modifiedAt: Date(timeIntervalSince1970: 1_700_000_100)
        )
        let emptyNote = Note(
            paperID: paper.id,
            body: "  ",
            modifiedAt: Date(timeIntervalSince1970: 1_700_000_200)
        )

        let content = PaperDigestExportPolicy.makeContent(
            paper: paper,
            notes: [emptyNote, keptNote],
            exportDate: exportDate
        )

        XCTAssertNotNil(content)
        XCTAssertEqual(content?.notes.count, 1)

        let markdown = PaperDigestExportPolicy.makeMarkdown(
            content: try XCTUnwrap(content),
            bundle: Bundle(for: Self.self)
        )

        XCTAssertTrue(markdown.contains("# A Test Paper"))
        XCTAssertTrue(markdown.contains("**Source**: [arXiv 2303.08774](https://arxiv.org/abs/2303.08774)"))
        XCTAssertTrue(markdown.contains("**Authors**: Ada Lovelace, Alan Turing"))
        XCTAssertTrue(markdown.contains("> This is the abstract."))
        XCTAssertTrue(markdown.contains("> It has a second line."))
        XCTAssertTrue(markdown.contains("**Page**: 3"))
        XCTAssertTrue(markdown.contains("> Important quote"))
        XCTAssertTrue(markdown.contains("My reading note"))
        XCTAssertFalse(markdown.contains("  \n"))
    }

    func testCustomTemplateReplacesKnownPlaceholdersAndLeavesUnknownPlaceholders() throws {
        let exportDate = Date(timeIntervalSince1970: 1_700_000_000)
        let paper = Paper(
            doi: "10.1234/example",
            title: "A Test Paper",
            abstractText: "Abstract body",
            authors: ["Ada Lovelace"]
        )
        let note = Note(
            paperID: paper.id,
            body: "Template note",
            modifiedAt: Date(timeIntervalSince1970: 1_700_000_100)
        )
        let content = try XCTUnwrap(PaperDigestExportPolicy.makeContent(
            paper: paper,
            notes: [note],
            exportDate: exportDate
        ))

        let markdown = PaperDigestExportPolicy.makeMarkdown(
            content: content,
            bundle: Bundle(for: Self.self),
            template: """
            title={{title}}
            slug={{slug}}
            date={{dateISO}}
            authors={{authors}}
            identifier={{identifier}}
            source={{sourceTitle}} {{sourceURL}}
            {{metadataBlock}}
            {{abstractBlock}}
            {{notesBlock}}
            {{generatedBy}}
            {{unknown}}
            """
        )

        XCTAssertTrue(markdown.contains("title=A Test Paper"))
        XCTAssertTrue(markdown.contains("slug=a-test-paper"))
        XCTAssertTrue(markdown.contains("date=2023-11-14T22:13:20Z"))
        XCTAssertTrue(markdown.contains("authors=Ada Lovelace"))
        XCTAssertTrue(markdown.contains("identifier=DOI: 10.1234/example"))
        XCTAssertTrue(markdown.contains("source=DOI 10.1234/example https://doi.org/10.1234/example"))
        XCTAssertTrue(markdown.contains("**Source**: [DOI 10.1234/example](https://doi.org/10.1234/example)"))
        XCTAssertTrue(markdown.contains("## Abstract"))
        XCTAssertTrue(markdown.contains("> Abstract body"))
        XCTAssertTrue(markdown.contains("## Notes"))
        XCTAssertTrue(markdown.contains("Template note"))
        XCTAssertTrue(markdown.contains("Generated by Freddie"))
        XCTAssertTrue(markdown.contains("{{unknown}}"))
    }

    func testEmptyTemplateFallsBackToDefaultMarkdown() throws {
        let exportDate = Date(timeIntervalSince1970: 1_700_000_000)
        let paper = Paper(title: "Fallback Paper", authors: ["Ada Lovelace"])
        let content = try XCTUnwrap(PaperDigestExportPolicy.makeContent(
            paper: paper,
            notes: [],
            exportDate: exportDate
        ))

        let defaultMarkdown = PaperDigestExportPolicy.makeMarkdown(
            content: content,
            bundle: Bundle(for: Self.self)
        )
        let fallbackMarkdown = PaperDigestExportPolicy.makeMarkdown(
            content: content,
            bundle: Bundle(for: Self.self),
            template: " \n\t "
        )

        XCTAssertEqual(fallbackMarkdown, defaultMarkdown)
    }

    func testFileNameUsesDatePrefixAndReadableSlug() {
        let exportDate = Date(timeIntervalSince1970: 1_700_000_000)

        let fileName = PaperDigestExportPolicy.makeFileName(
            title: "Attention Is All You Need: 重新阅读",
            exportDate: exportDate
        )

        XCTAssertTrue(fileName.hasSuffix("-attention-is-all-you-need-重新阅读.md"))
        XCTAssertNotNil(
            fileName.range(
                of: #"^\d{4}-\d{2}-\d{2}-attention-is-all-you-need-重新阅读\.md$"#,
                options: .regularExpression
            )
        )
    }

    func testExportWithoutConfiguredDirectoryThrows() throws {
        let defaults = try makeIsolatedDefaults()
        let paper = Paper(title: "No Directory Paper")
        let content = try XCTUnwrap(PaperDigestExportPolicy.makeContent(paper: paper, notes: []))
        let exporter = PaperDigestExporter(
            configuration: PaperDigestExportConfiguration(userDefaults: defaults),
            fileManager: .default
        )

        XCTAssertThrowsError(try exporter.export(content: content, bundle: Bundle(for: Self.self))) { error in
            XCTAssertEqual(error as? PaperDigestExportError, .missingExportDirectory)
        }
    }

    func testUniqueExportFileURLAppendsNumericSuffix() throws {
        let firstURL = tempDirectory.appendingPathComponent("digest.md")
        let secondURL = tempDirectory.appendingPathComponent("digest-2.md")
        try "existing".write(to: firstURL, atomically: true, encoding: .utf8)
        try "existing".write(to: secondURL, atomically: true, encoding: .utf8)

        let uniqueURL = PaperDigestExportPolicy.uniqueExportFileURL(
            directoryURL: tempDirectory,
            preferredFileName: "digest.md"
        )

        XCTAssertEqual(uniqueURL.lastPathComponent, "digest-3.md")
    }

    func testExporterWritesMarkdownToConfiguredDirectory() throws {
        let defaults = try makeIsolatedDefaults()
        let configuration = PaperDigestExportConfiguration(userDefaults: defaults)
        try configuration.saveExportDirectory(tempDirectory)

        let exportDate = Date(timeIntervalSince1970: 1_700_000_000)
        let paper = Paper(title: "Configured Directory Paper", authors: ["Ada Lovelace"])
        let content = try XCTUnwrap(PaperDigestExportPolicy.makeContent(
            paper: paper,
            notes: [],
            exportDate: exportDate
        ))
        let expectedFirstURL = tempDirectory.appendingPathComponent(
            PaperDigestExportPolicy.makeFileName(title: content.title, exportDate: exportDate)
        )
        try "existing".write(to: expectedFirstURL, atomically: true, encoding: .utf8)

        let exportedURL = try PaperDigestExporter(
            configuration: configuration,
            fileManager: .default
        ).export(content: content, bundle: Bundle(for: Self.self))

        let expectedConflictBaseName = expectedFirstURL.deletingPathExtension().lastPathComponent
        XCTAssertEqual(exportedURL.lastPathComponent, "\(expectedConflictBaseName)-2.md")
        XCTAssertTrue(FileManager.default.fileExists(atPath: exportedURL.path))
        let markdown = try String(contentsOf: exportedURL, encoding: .utf8)
        XCTAssertTrue(markdown.contains("# Configured Directory Paper"))
    }

    private func makeIsolatedDefaults() throws -> UserDefaults {
        let suiteName = "ReadPaperTests.\(UUID().uuidString)"
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suiteName))
        defaults.removePersistentDomain(forName: suiteName)
        return defaults
    }
}
